services:
    mabs_jquery_ajax.twig.jquery_ajax_extension:
        class: Mabs\JqueryAjaxBundle\Twig\JqueryAjaxExtension
        arguments: []
        tags:
            - { name: twig.extension }
        public: false