services:
    symbundle_jquery_ajax_enx.twig.jquery_ajax_enx_extensio:
        class: SymBundle\JQueryAjaxEnxBundle\Twig\JqueryAjaxEnxExtension
        arguments: []
        tags:
            - { name: twig.extension }
        public: false
