services:
    symbundle_jquery_ajax.twig.jquery_ajax_extension:
        class: SymBundle\JQueryAjaxBundleEnx\Twig\JqueryAjaxExtensionEnx
        arguments: []
        tags:
            - { name: twig.extension }
        public: false
